// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/web-home/Bold.tsx": () => import("../components/mockups/web-home/Bold.tsx"),
  "./components/mockups/web-home/Modern.tsx": () => import("../components/mockups/web-home/Modern.tsx"),
  "./components/mockups/web-home/Warm.tsx": () => import("../components/mockups/web-home/Warm.tsx")
};
