// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-dash/Clean.tsx": () => import("../components/mockups/admin-dash/Clean.tsx"),
  "./components/mockups/admin-dash/Command.tsx": () => import("../components/mockups/admin-dash/Command.tsx"),
  "./components/mockups/admin-dash/Glass.tsx": () => import("../components/mockups/admin-dash/Glass.tsx")
};
