name: Build & Lint

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          production_aws_role_arn: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
          staging_aws_role_arn: ${{ secrets.STAGING_AWS_ROLE_ARN }}

      - name: Typecheck
        run: pnpm run typecheck

  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          production_aws_role_arn: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
          staging_aws_role_arn: ${{ secrets.STAGING_AWS_ROLE_ARN }}

      - name: Biome
        run: pnpm exec biome check ./apps ./packages

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          production_aws_role_arn: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
          staging_aws_role_arn: ${{ secrets.STAGING_AWS_ROLE_ARN }}

      - name: Build
        run: pnpm build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup
        with:
          production_aws_role_arn: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
          staging_aws_role_arn: ${{ secrets.STAGING_AWS_ROLE_ARN }}

      - name: Lint
        run: pnpm lint
